# Generated by Django 6.1 on 2026-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='moneda',
            field=models.CharField(default='PEN', max_length=3),
        ),
    ]
