# Generated by Django 6.1 on 2026-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='operacion',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], default='COMPRA', max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(default='FACTURA', max_length=20),
        ),
    ]
